site_title = "Lab-arXiv"
limit_days = 7
cache_url = "https://hkust-ai-lab.github.io/Lab-arXiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
